config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end 

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  validates :text, presence: true
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_save :update_posts_counter
  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def recent_posts
    posts.includes(:author).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      flash[:notice] = 'Comment added successfully!'
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      flash[:alert] = "Couln't add Comment!"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    if @like.save
      flash[:notice] = 'Like added successfully!'
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      flash[:alert] = "Couln't add a like!"
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes([:posts]).find(params[:user_id])
    @posts = @user.posts.includes([:comments]).order(created_at: :asc)
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:notice] = 'Post created successfully!'
      redirect_to user_posts_path(current_user)
    else
      flash[:alert] = "Couln't create post!"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(created_at: :asc)
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div class="form-container border-black">
  <h1>New Comment</h1>

  <%= form_with model: @comment, url: user_post_comments_path, class: "form", local: true do |form| %>
    <div class="form-items">
      <%= form.text_area :text, class: "form-fields border-black form-text", placeholder: "Write a comment..." %>
    </div>
    <div>
      <%= form.submit "Create comment", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "user", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "post", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "comment", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section>
  <%= render partial: "shared/user", locals: { user: @user } %>
  <% @posts.each do |post| %>
    <%= link_to user_post_path(user_id: post.author.id, id: post.id), class: "post" do %>
      <%= render "shared/post", post: post %>
      <div class="comments">
        <%= render "shared/comment", post: post %>
      </div>
    <% end %>
  <% end %>
  <button type="button" class="btn">Pagination</button>
</section>

app/views/posts/new.html.erb
<div class="form-container border-black">
  <h1>New Post</h1>

  <%= render "shared/form", post: @post %>

  <p class="back"><%=link_to 'Back to posts', user_posts_path %></p>
<div>

app/views/posts/show.html.erb
<section class="full-post-section">
  <div class="full-post border-black">
     <h2>Post # <%= @post.id %>: <%= @post.title %> by <%= @post.author.name %></h2>
    <p class="post-likes-comments">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
    <p><%= @post.text %></p>
        <div class="like-comment-btn">
      <%= form_with model: @like, url: user_post_likes_path(user_id: @post.author.id, post_id: @post.id), local: true do |form| %>
        <%= form.submit "Add a like", class: "btn" %>
      <% end %>
      <button type="button" class="btn"><%= link_to "Add a comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id)  %></button>
    </div>
  </div>
  <div class="comments">
    <%= render "shared/comment", post: @post %>
  </div>
</section>

app/views/shared/_comment.html.erb
<% if (post.comments.empty?) %>
  <p>No comment yet.</p>
<% else %>
  <% post.recent_comments.each do |comment| %>
    <ul>
      <li><%= comment.author.name %>: <%= comment.text %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: post, url: user_posts_path, local: true, class: "form" do |form| %>
  <div class="form-items">
    <%= form.label :title %></br>
    <%= form.text_field :title, class: "form-fields border-black form-title" %>
  </div>
  <div class="form-items">
    <%= form.label :text %></br>
    <%= form.text_area :text, class: "form-fields border-black form-text" %>
  </div>
  <div>
    <%= form.submit "Create post", class: "btn" %>
  </div>
<% end %>

app/views/shared/_post.html.erb
<div class="user-post border-black">
  <h2>Post #<%= post.id %></h2> : <%= post.title %></h2>
  <p><%= truncate(post.text, length: 150, omission: "...") %></p>
  <div class="like-comment">
    <p>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p> 
  </div>
</div>

app/views/shared/_user.html.erb
<%= link_to user_path(user), class: "user-list-item" do %>
  <img src="<%= user.photo %>" alt="avatar" class="border-black">
  <div class="user-info border-black">
    <h2><%= user.name %></h2>
    <p>No. of posts: <%= user.posts_counter %></p>
  </div>
<% end %>

app/views/users/index.html.erb
<section>
<h1>List of users:</h1>
  <%= render partial: "shared/user", collection: @users, as: :user %>
</section>

app/views/users/show.html.erb
<section>
  <%= render "shared/user", user: @user %>
  <div class="bio border-black">
    <p>Bio</p>
    <p><%= @user.bio %></p>
  </div>
  <div class="posts">
    <% @recent_posts.each do |post| %>
      <%= link_to user_post_path(user_id: post.author.id, id: post.id), class: "post" do %>
        <%= render "shared/post", post: post %>
      <% end %>
    <% end %>
  </div>
  <button type="button" class="btn"><%= link_to "See all posts", user_posts_path(@user)  %></button>
  <button type="button" class="btn"><%= link_to "Create a post", new_user_post_path(@user)  %></button>
</section>